### PR TITLE
Support L/R-specified modifiers

### LINKED ISSUE #15: want to distinguish left/right modifier keys
I wanted to use Control_R to emacs key-binds and Control_L to standard key-binds.

I modified the key.py like following and successfully realized what I wanted.

    @classmethod
    def _get_modifier_map(cls):
        return {
            # cls.CONTROL: {Key.LEFT_CTRL, Key.RIGHT_CTRL},
            cls.CONTROL: {Key.RIGHT_CTRL},
            cls.ALT: {Key.LEFT_ALT, Key.RIGHT_ALT},
            .....

However, it will be better if we can specify right/left modifiers separately like: CR-a / CL-a, ShiftR-a/ShiftL-a, and so on.

### PR DESCRIPTION
**Pull request by amaya382**
resolve #15 
Support L/R-specified Control, Alt, Shift and Super by expanding modifiers

NOTE: Works for me w/ handmade a bit complex cases such as nested mappings, mixed modifiers (L/R-specified and not specified), including raw keys, etc.
But not perfect test cases :(

### CODE REVIEW

**Comment by mooz** [comment]
great! thanks a lot!

**Comment by rbreaves** [comment]
@amaya382 Would you have any thoughts on how to prevent the modifier keys from releasing until the user actually releases the physical modifier they're holding down initially? The simple combo behavior it has right now does not work well for Alt-Tab Window switching or tabs in certain apps like Sublime Text.

https://github.com/mooz/xkeysnail/issues/70

**Comment by amaya382** [comment]
@rbreaves I'm sorry, I don't know around pressing/releasing events.
I guess [it](https://github.com/mooz/xkeysnail/blob/master/xkeysnail/output.py) is related, and its contributors may know about it.

**Comment by rbreaves** [comment]
@amaya382 I'll take another look at that file, I do think I see something I could try now. And thanks for your contributions to this project, had you not added the Left and Right modifiers it would actually make what I am attempting to do rather impossible. (At least via this method, I have a good enough understanding of xkb at this point, but I want something simpler that what I have been working with.)

**Comment by rbreaves** [comment]
@amaya382 Looks like I managed to fix it, it was in the output and transform files that needed modifying. I don't think my update breaks anything else, but I have not tested it just a whole lot yet. In my use cases though it appears to be very stable working as I would want and expect a remapper to do.

https://github.com/mooz/xkeysnail/pull/71

**Pull request merged**
